spring:
  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/engx}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:}

  jpa:
    hibernate:
      ddl-auto: update
      show-sql: true

  messages:
    basename: messages/api_error_messages

springdoc:
  show-actuator: true
  paths-to-match: /**
  packages-to-scan: com.engx.engxserver

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET}
      expiration: ${ACCESS_TOKEN_EXPIRE}
      refresh-token:
        expiration: ${REFRESH_TOKEN_EXPIRE}

  azure:
    endpoint: ${AZURE_ENDPOINT}
    api-key: ${AZURE_API_KEY}